######################################################################
# Automatically generated by qmake (3.0) ?? ????. 26 10:45:11 2018
######################################################################

TEMPLATE = app
TARGET = vscode
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT+=widgets